#!/bin/bash
## https://docs.docker.com/docker-hub/builds/advanced/

## Rleases must be of the following pattern v1.17.6 or v1.17.6-r1 only!
#

IFS=' ' read -r -a flavours <<< "${FLAVOURS:-_}"
IFS='-' read -r -a parts <<< "$GIT_BRANCH"
version=${parts[0]}
release=${parts[1]}

## Print a release list (tag docker) pairs, like bellow:
#   v1.17.6-r0 Dockerfile
#   v1.17.6-gcloud-r0 Dockerfile.gcloud
#
release_list() {
  local flavour dockerfile
  for flavour in ${flavours[@]}; do
    dockerfile="Dockerfile.$flavour"
    dockerfile="${dockerfile%._}"
    tag="${version}-${flavour}-${release}"
    tag=$(echo $tag | sed 's/-_-/-/')

    echo $tag $dockerfile
  done
}

release_list | while read line; do
  read tag dockerfile <<< $(echo $line)
  echo docker build \
    --build-arg KUBECTL_VERSION=$version -t $DOCKER_REPO:$tag -f $dockerfile
done
