#!/bin/bash
## https://docs.docker.com/docker-hub/builds/advanced/

## GIT_BRANCH equals both invoking branch or tag.
## Strip of a release suffix
version="${GIT_BRANCH%-r*}" # strip suffix r12 (-r*)

## build image
docker build \
  --build-arg KUBECTL_VERSION=$version \
  -t ${IMAGE_NAME} .
