#!/bin/bash
## https://docs.docker.com/docker-hub/builds/advanced/

## Releases the image with a new tag
release_image() {
  local newtag="$1"
  if [ ${IMAGE_NAME} != "${DOCKER_REPO}:${newtag}" ]; then
    docker image tag ${IMAGE_NAME} "${DOCKER_REPO}:${newtag}"
    docker image push "${DOCKER_REPO}:${newtag}"
  fi
}

## release image with a release stripped stripped
stripped_tag="${GIT_BRANCH%-r*}"
release_image $stripped_tag

## release image with a stripped patch version
stripped_patch="${stripped_tag%.*}"
release_image $stripped_patch

## update microbadger
if [ -n "$MICROBADGER_TOKEN" ]; then
  curl -XPOST "https://hooks.microbadger.com/images/${DOCKER_REPO}/${MICROBADGER_TOKEN}"
fi
