#!/bin/bash
## https://docs.docker.com/docker-hub/builds/advanced/

. ./hooks/.helpers

IFS='-' read -r -a parts <<< "$SOURCE_BRANCH"
version=${parts[0]}
release=${parts[1]}

## Make additional image tags and push them
tag_and_push() {
  local basetag=$1 tag
  shift

  for tag in $@; do
    docker image tag $DOCKER_REPO:$basetag ${DOCKER_REPO}:$tag
    docker image push ${DOCKER_REPO}:$tag
  done
}

release_list_from_template Dockerfile.gotmpl | \
while read line; do
  read tag dockerfile <<< "$line"

  stripped_release="${tag%-r*}"
  stripped_patch=$(echo $stripped_release | sed -r 's/^(v[0-9]+.[0-9]+).[0-9]+/\1/')
  tag_and_push $tag $stripped_release $stripped_patch
done

## update microbadger
if [ -n "$MICROBADGER_TOKEN" ]; then
  curl -XPOST "https://hooks.microbadger.com/images/${DOCKER_REPO#index.docker.io/}/${MICROBADGER_TOKEN}"
fi
