#!/bin/bash
## https://docs.docker.com/docker-hub/builds/advanced/

IFS=' ' read -r -a flavours <<< "${FLAVOURS:-_}"
IFS='-' read -r -a parts <<< "$GIT_BRANCH"
version=${parts[0]}
release=${parts[1]}

## Print a release list (tag docker) pairs, like bellow:
#   v1.17.6-r0 Dockerfile
#   v1.17.6-gcloud-r0 Dockerfile.gcloud
#
release_list() {
  local flavour dockerfile
  for flavour in ${flavours[@]}; do
    dockerfile="Dockerfile.$flavour"
    dockerfile="${dockerfile%._}"
    tag="${version}-${flavour}-${release}"
    tag=$(echo $tag | sed -e 's/-_-/-/' -e 's/-$//')

    echo $tag $dockerfile
  done
}

## Make additional image tags and push them
tag_and_push() {
  local basetag=$1 tag
  shift

  for tag in $@; do
    docker image tag $DOCKER_REPO:$basetag ${DOCKER_REPO}:$tag
    docker image push ${DOCKER_REPO}:$tag
  done
}

release_list | while read line; do
  read tag dockerfile <<< "$line"

  stripped_release="${tag%-r*}"
  stripped_patch=$(echo $stripped_release | sed -r 's/^(v[0-9]+.[0-9]+).[0-9]+/\1/')
  tag_and_push $tag $stripped_release $stripped_patch
done

## update microbadger
if [ -n "$MICROBADGER_TOKEN" ]; then
  curl -XPOST "https://hooks.microbadger.com/images/${DOCKER_REPO}/${MICROBADGER_TOKEN}"
fi
